### ISSUE TITLE
Dataset & Dashboard Brainstorming

### ISSUE THREAD

**Issue by mmaidana24318** [UBC-MDS/group16#1]

**Comment by mmaidana24318** [comment]
Greenhouse gas emissions in Canada
https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2020008-eng.htm#datavisualization

This dashboard could be interesting for planning actions in an NGO working on climate change. Some questions we could help respond would be: which industries/sectors are the generating more emissions? which provinces need more traction to decrease emissions? do households follow industries trends?

**Comment by ciciecho-ds** [comment]
World Happiness Report
https://www.kaggle.com/ajaypalsinghlo/world-happiness-report-2021

Audience: global policy makers
We can make a dashboard answering questions such as: what are the world's happiest countries according to the report?
What factors seem to contribute the most to happiness? What are the trends in the world's happiness 2005? What are the differences in happiness and happiness factors among the world's different regions and countries?

**Comment by sy25wang** [comment]
Crime in Vancouver
https://geodash.vpd.ca/opendata/#

Audience: Vancouver Police Department
The data can be used to present frequency of crimes (pie or bar chart), time distribution (bar char), trends of total crimes (line plot) to give the police department a better overview of security situation of the city for better planning. Questions can be answered include: what the most frequent crimes happened in Vancouver? Is the crime rate increasing or decreasing over the past few years? Which neighbourhood has the most crimes ocurred?

**Comment by paradise1260** [comment]
Online shoppers purchasing intention

[https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset](https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset)

The data contains different features which help us determine if the customer will purchase or not. There are a mixture of categorical and numeric features. Some questions that can be answered via the dashboard:

1. Are the customers who shop on weekends going to purchase products or the customers who shop during the week?
2. Which months are more revenue-making by the customers?
3. Will customers purchase more on Special Days?
4. What is the distribution of Exit Rates for the customers who end up purchasing?

**Comment by sy25wang** [comment]
We will go with `Crime in Vancouver` dataset.
