### ISSUE TITLE
Description of your app & sketch

### ISSUE THREAD

**Issue by sy25wang** [UBC-MDS/group16#8]

**Comment by paradise1260** [comment]
The plots include:

1. Hopefully a map of all the neighborhoods and number of crimes
2. A time series of crimes for different neighborhoods over past 5 hours
3. Crime types for each neighborhood 
4. Pie charts for type of crimes 
5. Summary statistics

**Comment by mmaidana24318** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/88546099/154211090-9d4812af-79aa-4d0d-ad0b-3d7879d2448e.png">

**Comment by mmaidana24318** [comment]
![image](https://user-images.githubusercontent.com/88546099/154211190-e16b52a0-ed11-40b8-89bf-84c8773ff9d0.png)

**Comment by mmaidana24318** [comment]
Version 3 

![image](https://user-images.githubusercontent.com/88546099/154356733-8a1c349c-4c9c-4fd9-acda-f6349029adbb.png)

**Comment by sy25wang** [comment]
These visuals look fantastic! I agree with @paradise1260 on #3, make sure in the paragraph we state the time period for the `total # of crimes` is for selected `years` parameter to avoid some confusions. Well done @mmaidana24318 !
